# Generated by Django 5.2.5 on 2025-08-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('desktop', 'Desktop Computer'), ('laptop', 'Laptop'), ('server', 'Server'), ('network', 'Network Device'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('monitor', 'Monitor'), ('ups', 'UPS'), ('peripheral', 'Peripheral Device')], default='desktop', help_text='Select the category of the equipment.', max_length=20),
        ),
    ]
