# Generated by Django 5.2.5 on 2025-08-13 07:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_equipment_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='intervention',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'Intervention', 'verbose_name_plural': 'Interventions'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['software__name', 'expiration_date'], 'verbose_name_plural': 'Licenses'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['name'], 'verbose_name_plural': 'Software'},
        ),
        migrations.RenameField(
            model_name='intervention',
            old_name='date',
            new_name='scheduled_date',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='address',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='license',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='license',
            name='related_equipment',
        ),
        migrations.AddField(
            model_name='equipment',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(blank=True, help_text='Physical condition notes', max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='hostname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='next_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_order',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='specifications',
            field=models.TextField(blank=True, help_text='Technical specifications'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='supplier',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='intervention',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='parts_used',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='intervention',
            name='requires_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='intervention',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intervention',
            name='title',
            field=models.CharField(default='Intervention Title', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='license',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='installed_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_licenses', to='assets.equipment'),
        ),
        migrations.AddField(
            model_name='license',
            name='order_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='license',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='seats',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('unassigned', 'Unassigned'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='building',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='floor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='software',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='software',
            name='is_cloud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='software',
            name='license_type',
            field=models.CharField(choices=[('perpetual', 'Perpetual'), ('subscription', 'Subscription'), ('open_source', 'Open Source'), ('trial', 'Trial')], default='subscription', max_length=20),
        ),
        migrations.AddField(
            model_name='software',
            name='minimum_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='software',
            name='support_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='software',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='asset_tag',
            field=models.CharField(default='Default Title', help_text='Unique asset identification tag', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('desktop', 'Desktop Computer'), ('laptop', 'Laptop'), ('server', 'Server'), ('network', 'Network Device'), ('printer', 'Printer'), ('scanner', 'Scanner'), ('monitor', 'Monitor'), ('ups', 'UPS'), ('peripheral', 'Peripheral Device'), ('other', 'Other Equipment')], default='desktop', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='assets.location'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Maintenance'), ('retired', 'Retired'), ('lost', 'Lost/Stolen')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='license',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['asset_tag'], name='assets_equi_asset_t_8a17a8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['serial_number'], name='assets_equi_serial__8b6fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status'], name='assets_equi_status_3da1ae_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['category'], name='assets_equi_categor_fe3629_idx'),
        ),
    ]
